spring.application.name=HaberSitesiSistemi
spring.datasource.url=jdbc:postgresql://localhost:5432/haber_sitesi
spring.config.import=optional:classpath:application-secret.properties,optional:file:./config/application-secret.properties
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Media Upload
app.upload.dir=uploads/media
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT
app.jwt.expiration-ms=86400000
app.jwt.refresh-expiration-ms=604800000

# Session
server.servlet.session.timeout=10m

# Thymeleaf
spring.thymeleaf.cache=true
spring.thymeleaf.encoding=UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true

# GMAIL SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
